name: axetop_test_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  objectdb: ^1.2.1+1
  path_provider: ^2.0.2
  provider: ^5.0.0
  xml: ^5.1.2

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:

  uses-material-design: true